name: PMD Code Analysis

on:
  push:
    branches:
      - "**"

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run PMD analysis
        uses: pmd/pmd-github-action@v1
        with:
          rulesets: 'rulesets/java/quickstart.xml'
          version: '7.0.0-rc4'
